name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            setup.py
      - name: Install deps
        run: python -m pip install -r requirements-dev.txt

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3 

      - name: Configure & Push via Git
        run: |
          git config user.name "pre-commit bot"
          git pull
          git add .
          git commit -m "style: pre-commit fixes"
          git push